"""Tests for raw-FVG splits generated by scripts/data/build_rawfvg_splits.py.

These tests run AFTER build_rawfvg_splits.py has been executed.
They assert structural correctness of the generated parquets and class weights.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

RAWFVG_DIR = Path("data/processed/rawfvg")
SPLITS = ["train", "val", "test"]


@pytest.mark.skipif(
    not (RAWFVG_DIR / "spy_h1_train.parquet").exists(),
    reason="Raw-FVG splits not yet generated — run scripts/data/build_rawfvg_splits.py first",
)
class TestRawFVGSplitsExist:
    def test_parquet_files_exist(self):
        for split in SPLITS:
            path = RAWFVG_DIR / f"spy_h1_{split}.parquet"
            assert path.exists(), f"Missing: {path}"

    def test_class_weights_json_exists(self):
        path = RAWFVG_DIR / "class_weights_rawfvg.json"
        assert path.exists(), f"Missing: {path}"


@pytest.mark.skipif(
    not (RAWFVG_DIR / "class_weights_rawfvg.json").exists(),
    reason="Raw-FVG splits not yet generated",
)
class TestRawFVGClassWeights:
    def test_weights_json_keys(self):
        with open(RAWFVG_DIR / "class_weights_rawfvg.json") as fh:
            data = json.load(fh)
        assert set(data.keys()) == {"0", "1", "2"}, f"Unexpected keys: {data.keys()}"

    def test_minority_classes_have_higher_weight(self):
        with open(RAWFVG_DIR / "class_weights_rawfvg.json") as fh:
            data = json.load(fh)
        none_w = float(data["0"])
        bull_w = float(data["1"])
        bear_w = float(data["2"])
        assert bull_w > none_w, f"Bull weight {bull_w} should exceed none weight {none_w}"
        assert bear_w > none_w, f"Bear weight {bear_w} should exceed none weight {none_w}"

    def test_weights_are_positive(self):
        with open(RAWFVG_DIR / "class_weights_rawfvg.json") as fh:
            data = json.load(fh)
        for k, v in data.items():
            assert float(v) > 0, f"Weight for class {k} is not positive: {v}"


@pytest.mark.skipif(
    not (RAWFVG_DIR / "spy_h1_train.parquet").exists(),
    reason="Raw-FVG splits not yet generated",
)
class TestRawFVGPositiveRate:
    def test_positive_rate_in_expected_range(self):
        """Raw FVG ~25% positive rate expected — gate A1 confirmed 5–40%."""
        df = pd.read_parquet(RAWFVG_DIR / "spy_h1_train.parquet")
        assert "label" in df.columns, "Missing 'label' column in train parquet"
        total = len(df)
        pos = int((df["label"] != 0).sum())
        rate = pos / max(1, total)
        assert 0.05 <= rate <= 0.40, (
            f"Positive rate {rate:.3%} outside expected 5–40% range. "
            "Expected ~25% for raw FVG. Possible labelling error."
        )

    def test_labels_are_in_valid_range(self):
        for split in SPLITS:
            df = pd.read_parquet(RAWFVG_DIR / f"spy_h1_{split}.parquet")
            invalid = df["label"][~df["label"].isin([0, 1, 2])]
            assert len(invalid) == 0, (
                f"Split '{split}' has {len(invalid)} labels outside {{0,1,2}}: {invalid.unique()}"
            )

    def test_no_nan_labels(self):
        for split in SPLITS:
            df = pd.read_parquet(RAWFVG_DIR / f"spy_h1_{split}.parquet")
            assert not df["label"].isna().any(), f"NaN labels in split '{split}'"
